import type { ImageSourcePropType } from 'react-native';

/** Fotos empacotadas no app (CC0, ilustrativas; créditos em assets/photos/CREDITS.md). */
export const PHOTOS: Record<string, ImageSourcePropType> = {
  'camera-monitor': require('../../assets/photos/camera-monitor.jpg'),
  'camera-tripe': require('../../assets/photos/camera-tripe.jpg'),
  'camera-vermelha': require('../../assets/photos/camera-vermelha.jpg'),
  'camera-vintage': require('../../assets/photos/camera-vintage.jpg'),
  'casamento-banco': require('../../assets/photos/casamento-banco.jpg'),
  'casamento-lago': require('../../assets/photos/casamento-lago.jpg'),
  'casamento-maos': require('../../assets/photos/casamento-maos.jpg'),
  'cinegrafista-camera': require('../../assets/photos/cinegrafista-camera.jpg'),
  'cinegrafista-escada': require('../../assets/photos/cinegrafista-escada.jpg'),
  'claquete': require('../../assets/photos/claquete.jpg'),
  'drone-floresta': require('../../assets/photos/drone-floresta.jpg'),
  'drone-mar': require('../../assets/photos/drone-mar.jpg'),
  'drone-rio': require('../../assets/photos/drone-rio.jpg'),
  'edicao-estudio': require('../../assets/photos/edicao-estudio.jpg'),
  'edicao-laptop': require('../../assets/photos/edicao-laptop.jpg'),
  'equipamentos': require('../../assets/photos/equipamentos.jpg'),
  'estudio-set': require('../../assets/photos/estudio-set.jpg'),
  'fotografo-penhasco': require('../../assets/photos/fotografo-penhasco.jpg'),
  'gravacao-gimbal': require('../../assets/photos/gravacao-gimbal.jpg'),
  'litoral-ilha': require('../../assets/photos/litoral-ilha.jpg'),
  'mesa-som': require('../../assets/photos/mesa-som.jpg'),
  'microfone-estudio': require('../../assets/photos/microfone-estudio.jpg'),
  'palco-camera': require('../../assets/photos/palco-camera.jpg'),
  'palco-fumaca': require('../../assets/photos/palco-fumaca.jpg'),
  'palmeiras': require('../../assets/photos/palmeiras.jpg'),
  'praia-coqueiros': require('../../assets/photos/praia-coqueiros.jpg'),
  'projetor': require('../../assets/photos/projetor.jpg'),
  'show-luzes': require('../../assets/photos/show-luzes.jpg'),
  'show-publico': require('../../assets/photos/show-publico.jpg'),
  'sol-drone': require('../../assets/photos/sol-drone.jpg'),
  'steadicam': require('../../assets/photos/steadicam.jpg'),
  'bia': require('../../assets/portraits/bia.jpg'),
  'caio': require('../../assets/portraits/caio.jpg'),
  'joana': require('../../assets/portraits/joana.jpg'),
  'marina': require('../../assets/portraits/marina.jpg'),
  'theo': require('../../assets/portraits/theo.jpg'),
};
